### ISSUE TITLE
Question: The same target want to build multi channel, independent link, not reused. 

### ISSUE THREAD

**Issue by CherishCai** [tikv/grpc-rs#589]
Question: Can I build multi channel with the same target? The same target-server with two clients with different responsibilities.
有两个不同职责的客户端而对应的相同的服务端，可以同一个目标地址，而产生两个不同链接的 Channel 吗？

```rust
let env = Arc::new(grpcio::Environment::new(2));
let channel = grpcio::ChannelBuilder::new(env)
    .reuse_port(false) // same target build multi channel, independent link, not reused.
    .connect(target.as_str());
```

grpcio = 0.11

#### 目前效果如下：
1.  target 一样，虽然使用 ChannelBuilder 构建了两次，而得到的链接是同一个。
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/16837364/192155725-24858bed-76e7-4a34-a5c3-f85c79802b3c.png">

2.  target 不一样，使用 ChannelBuilder 构建了两次，得到的链接是不同。
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/16837364/192156601-6b2a5df3-55a5-4abf-ad20-7a03a2977038.png">

#### 期望效果
无论 target 是否一样，使用 ChannelBuilder 构建了两次，得到两个不同的链接。

**Comment by BusyJay** [comment]
Channel is different from connection. By default, gRPC c core tends to reuse connections, connection pool more specifically, instead of one connection per channel. If you really want to use different connections for different channels object, you can set `GRPC_ARG_USE_LOCAL_SUBCHANNEL_POOL` to 1 by `builder = builder.raw_cfg_int(grpcio_sys::GRPC_ARG_USE_LOCAL_SUBCHANNEL_POOL.into(), 1)`.

**Comment by CherishCai** [comment]
> Channel is different from connection. By default, gRPC c core tends to reuse connections, connection pool more specifically, instead of one connection per channel. If you really want to use different connections for different channels object, you can set `GRPC_ARG_USE_LOCAL_SUBCHANNEL_POOL` to 1 by `builder = builder.raw_cfg_int(grpcio_sys::GRPC_ARG_USE_LOCAL_SUBCHANNEL_POOL.into(), 1)`.

Thanks, I will try later.
